<?php


namespace Plugin\Stripe4\Tests\Form\Admin\Stripe;


use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Plugin\Stripe4\Form\Type\Admin\Stripe\UserType;

class UserTypeTest extends AbstractTypeTestCase
{
    protected $form;

    protected $formData = [
        'public_key' => 'dummy',
        'secret_key' => 'dummy',
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form = $this->formFactory
            ->createBuilder(UserType::class, null, [
                'csrf_protection' => false
            ])
            ->getForm();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPUBLIC_KEYが空はエラー()
    {
        $this->formData['public_key'] = '';
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }

    public function testSECRET_KEYが空はエラー()
    {
        $this->formData['secret_key'] = '';
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }
}
