<?php
/**
 * This file is part of Plugin
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 * https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Stripe4\Tests\Form;


use Eccube\Entity\Customer;
use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Plugin\Stripe4\Entity\Team;
use Plugin\Stripe4\Form\Type\CardType;
use Plugin\Stripe4\Repository\TeamRepository;
use Symfony\Component\Form\FormInterface;

class CardTypeTest extends AbstractTypeTestCase
{
    /** @var FormInterface */
    protected $form;

    /** @var TeamRepository */
    protected $teamRepository;

    /** @var Team  */
    protected $team;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $container = self::$kernel->getContainer();

        $this->teamRepository = $container->get(TeamRepository::class);

        $Customer = $this->createCustomer();
        $this->team = $this->createTeam($Customer);

        $this->form = $this->formFactory
            ->createBuilder(CardType::class, null, [
                'csrf_protection' => false
            ])
            ->getForm();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test正常テスト()
    {
        $this->form->submit($this->team->getStripePaymentMethodId());
        self::assertTrue($this->form->isValid());
        self::assertEquals($this->form->getData(), $this->teamRepository->find($this->team->getId()));
    }

    protected function createTeam(Customer $customer)
    {
        $faker = $this->getFaker();

        $team = new Team();
        $team
            ->setCustomer($customer)
            ->setStripeCustomerId($faker->word)
            ->setStripePaymentMethodId($faker->word);
        $this->entityManager->persist($team);
        $this->entityManager->flush();

        return $team;
    }

}
